### ISSUE TITLE
css background image

### ISSUE THREAD

**Issue by Jarlaxle1979** [Jarlaxle1979/FGR#19]
I have added a background image to main.css

`.background 
    {
    	background: url("edbg.jpg");
        background-repeat: no-repeat;
        background-attachment: fixed;
    }`

The image is currently in the css folder but should be in /media/images...

When I do this, the image doesn't display because it needs to be relative to the css file.  I have tried the full file path and removed parts up to /media/images but it doesn't show.  Any ideas?

**Comment by PangolinPaw** [comment]
I can't test it from my tablet, but this path (including the dots) should work:

../media/images/background.png

**Comment by Jarlaxle1979** [comment]
The two dots are the significant part?

**Comment by Jarlaxle1979** [comment]
@PangolinPaw ignore me... i need to learn to read properly!

**Comment by Jarlaxle1979** [comment]
Worked perfectly, thanks
